apiVersion: skaffold/v2beta24
kind: Config
deploy:
  kubectl:
    manifests:
      - ./config/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: guilhermetupinamba/birdsquawk
      context: birdsquawk-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: guilhermetupinamba/front-end
      context: front-end
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
